Repository woorifisa/apply, pull requests merged in 2023-07, with the labels that each got.

#27 [feature] 레이아웃을 구성한다.
  frontend/src/assets/main.css
  frontend/src/constants/String.js
  frontend/src/layouts/DefaultFooter.vue
  frontend/src/layouts/DefaultHeader.vue
  frontend/src/layouts/DefaultLayout.vue
  frontend/src/router/index.js
Labels: 기능, 프론트엔드

#30 [fix] 웹페이지 너비에 따라 헤더 변경하도록 구현
  frontend/src/components/icons/HamburgerMenu.vue
  frontend/src/layouts/DefaultHeader.vue
Labels: 버그, 프론트엔드

#31 [Feature] 라우터와 기본 페이지를 생성한다.
  frontend/src/constants/String.js
  frontend/src/router/index.js
  frontend/src/views/ApplyView.vue
  frontend/src/views/ContactView.vue
  frontend/src/views/CourseView.vue
  frontend/src/views/HomeView.vue
  frontend/src/views/RecruitView.vue
Labels: 기능, 프론트엔드

#19 [feature] 모집을 추가해서 저장하는 테이블을 구현한다.
  backend/build.gradle
  backend/src/main/java/com/apply/BackendApplication.java
  backend/src/main/java/com/apply/admin/recruitment/controller/RecruitmentController.java
  backend/src/main/java/com/apply/admin/recruitment/domain/Recruitment.java
  backend/src/main/java/com/apply/admin/recruitment/domain/RecruitmentStatus.java
  backend/src/main/java/com/apply/admin/recruitment/dto/request/NewRecruitmentRequest.java
  backend/src/main/java/com/apply/admin/recruitment/dto/request/RecruitmentUpdateRequest.java
  backend/src/main/java/com/apply/admin/recruitment/dto/response/NewRecruitmentResponse.java
  backend/src/main/java/com/apply/admin/recruitment/dto/response/RecruitmentResponse.java
  backend/src/main/java/com/apply/admin/recruitment/exception/NoSuchRecruitmentException.java
  backend/src/main/java/com/apply/admin/recruitment/repository/RecruitmentRepository.java
  backend/src/main/java/com/apply/admin/recruitment/service/RecruitmentService.java
  backend/src/main/java/com/apply/common/BaseEntity.java
Labels: 기능, 백엔드
